/**
 * ComicStock.WebApi
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ComicStockwebApi);
  }
}(this, function(expect, ComicStockwebApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ComicStockwebApi.IssueDto();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('IssueDto', function() {
    it('should create an instance of IssueDto', function() {
      // uncomment below and update the code to test IssueDto
      //var instane = new ComicStockwebApi.IssueDto();
      //expect(instance).to.be.a(ComicStockwebApi.IssueDto);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instane = new ComicStockwebApi.IssueDto();
      //expect(instance).to.be();
    });

    it('should have the property title (base name: "title")', function() {
      // uncomment below and update the code to test the property title
      //var instane = new ComicStockwebApi.IssueDto();
      //expect(instance).to.be();
    });

    it('should have the property description (base name: "description")', function() {
      // uncomment below and update the code to test the property description
      //var instane = new ComicStockwebApi.IssueDto();
      //expect(instance).to.be();
    });

    it('should have the property seriesNumber (base name: "seriesNumber")', function() {
      // uncomment below and update the code to test the property seriesNumber
      //var instane = new ComicStockwebApi.IssueDto();
      //expect(instance).to.be();
    });

    it('should have the property publicationDate (base name: "publicationDate")', function() {
      // uncomment below and update the code to test the property publicationDate
      //var instane = new ComicStockwebApi.IssueDto();
      //expect(instance).to.be();
    });

    it('should have the property publisherId (base name: "publisherId")', function() {
      // uncomment below and update the code to test the property publisherId
      //var instane = new ComicStockwebApi.IssueDto();
      //expect(instance).to.be();
    });

    it('should have the property publisher (base name: "publisher")', function() {
      // uncomment below and update the code to test the property publisher
      //var instane = new ComicStockwebApi.IssueDto();
      //expect(instance).to.be();
    });

    it('should have the property creators (base name: "creators")', function() {
      // uncomment below and update the code to test the property creators
      //var instane = new ComicStockwebApi.IssueDto();
      //expect(instance).to.be();
    });

    it('should have the property stock (base name: "stock")', function() {
      // uncomment below and update the code to test the property stock
      //var instane = new ComicStockwebApi.IssueDto();
      //expect(instance).to.be();
    });

    it('should have the property thumbnail (base name: "thumbnail")', function() {
      // uncomment below and update the code to test the property thumbnail
      //var instane = new ComicStockwebApi.IssueDto();
      //expect(instance).to.be();
    });

    it('should have the property images (base name: "images")', function() {
      // uncomment below and update the code to test the property images
      //var instane = new ComicStockwebApi.IssueDto();
      //expect(instance).to.be();
    });

  });

}));
