/**
 * ComicStock.WebApi
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ComicStockwebApi);
  }
}(this, function(expect, ComicStockwebApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ComicStockwebApi.QualityInput();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('QualityInput', function() {
    it('should create an instance of QualityInput', function() {
      // uncomment below and update the code to test QualityInput
      //var instane = new ComicStockwebApi.QualityInput();
      //expect(instance).to.be.a(ComicStockwebApi.QualityInput);
    });

    it('should have the property fineQuantity (base name: "fineQuantity")', function() {
      // uncomment below and update the code to test the property fineQuantity
      //var instane = new ComicStockwebApi.QualityInput();
      //expect(instance).to.be();
    });

    it('should have the property veryFineQuantity (base name: "veryFineQuantity")', function() {
      // uncomment below and update the code to test the property veryFineQuantity
      //var instane = new ComicStockwebApi.QualityInput();
      //expect(instance).to.be();
    });

    it('should have the property goodQuantity (base name: "goodQuantity")', function() {
      // uncomment below and update the code to test the property goodQuantity
      //var instane = new ComicStockwebApi.QualityInput();
      //expect(instance).to.be();
    });

    it('should have the property poorQuantity (base name: "poorQuantity")', function() {
      // uncomment below and update the code to test the property poorQuantity
      //var instane = new ComicStockwebApi.QualityInput();
      //expect(instance).to.be();
    });

  });

}));
