/**
 * ComicStock.WebApi
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['./ApiClient', './model/CreatorDto', './model/IssueDto', './model/OrderDto', './model/OrderInput', './model/OrderItemDto', './model/OrderStockResponse', './model/QualityInput', './model/ResourceDto', './model/StockDto', './model/SupplierDto', './api/CreatorsApi', './api/IssuesApi', './api/OrdersApi', './api/SuppliersApi'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('./ApiClient'), require('./model/CreatorDto'), require('./model/IssueDto'), require('./model/OrderDto'), require('./model/OrderInput'), require('./model/OrderItemDto'), require('./model/OrderStockResponse'), require('./model/QualityInput'), require('./model/ResourceDto'), require('./model/StockDto'), require('./model/SupplierDto'), require('./api/CreatorsApi'), require('./api/IssuesApi'), require('./api/OrdersApi'), require('./api/SuppliersApi'));
  }
}(function(ApiClient, CreatorDto, IssueDto, OrderDto, OrderInput, OrderItemDto, OrderStockResponse, QualityInput, ResourceDto, StockDto, SupplierDto, CreatorsApi, IssuesApi, OrdersApi, SuppliersApi) {
  'use strict';

  /**
   * ERROR_UNKNOWN.<br>
   * The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
   * <p>
   * An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
   * <pre>
   * var ComicStockwebApi = require('index'); // See note below*.
   * var xxxSvc = new ComicStockwebApi.XxxApi(); // Allocate the API class we're going to use.
   * var yyyModel = new ComicStockwebApi.Yyy(); // Construct a model instance.
   * yyyModel.someProperty = 'someValue';
   * ...
   * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
   * ...
   * </pre>
   * <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
   * and put the application logic within the callback function.</em>
   * </p>
   * <p>
   * A non-AMD browser application (discouraged) might do something like this:
   * <pre>
   * var xxxSvc = new ComicStockwebApi.XxxApi(); // Allocate the API class we're going to use.
   * var yyy = new ComicStockwebApi.Yyy(); // Construct a model instance.
   * yyyModel.someProperty = 'someValue';
   * ...
   * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
   * ...
   * </pre>
   * </p>
   * @module index
   * @version v1
   */
  var exports = {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient: ApiClient,
    /**
     * The CreatorDto model constructor.
     * @property {module:model/CreatorDto}
     */
    CreatorDto: CreatorDto,
    /**
     * The IssueDto model constructor.
     * @property {module:model/IssueDto}
     */
    IssueDto: IssueDto,
    /**
     * The OrderDto model constructor.
     * @property {module:model/OrderDto}
     */
    OrderDto: OrderDto,
    /**
     * The OrderInput model constructor.
     * @property {module:model/OrderInput}
     */
    OrderInput: OrderInput,
    /**
     * The OrderItemDto model constructor.
     * @property {module:model/OrderItemDto}
     */
    OrderItemDto: OrderItemDto,
    /**
     * The OrderStockResponse model constructor.
     * @property {module:model/OrderStockResponse}
     */
    OrderStockResponse: OrderStockResponse,
    /**
     * The QualityInput model constructor.
     * @property {module:model/QualityInput}
     */
    QualityInput: QualityInput,
    /**
     * The ResourceDto model constructor.
     * @property {module:model/ResourceDto}
     */
    ResourceDto: ResourceDto,
    /**
     * The StockDto model constructor.
     * @property {module:model/StockDto}
     */
    StockDto: StockDto,
    /**
     * The SupplierDto model constructor.
     * @property {module:model/SupplierDto}
     */
    SupplierDto: SupplierDto,
    /**
     * The CreatorsApi service constructor.
     * @property {module:api/CreatorsApi}
     */
    CreatorsApi: CreatorsApi,
    /**
     * The IssuesApi service constructor.
     * @property {module:api/IssuesApi}
     */
    IssuesApi: IssuesApi,
    /**
     * The OrdersApi service constructor.
     * @property {module:api/OrdersApi}
     */
    OrdersApi: OrdersApi,
    /**
     * The SuppliersApi service constructor.
     * @property {module:api/SuppliersApi}
     */
    SuppliersApi: SuppliersApi
  };

  return exports;
}));
