/**
 * ComicStock.WebApi
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd && false) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/IssueDto', 'model/OrderItemDto'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./IssueDto'), require('./OrderItemDto'));
  } else {
    // Browser globals (root is window)
    if (!root.ComicStockwebApi) {
      root.ComicStockwebApi = {};
    }
    root.ComicStockwebApi.OrderDto = factory(root.ComicStockwebApi.ApiClient, root.ComicStockwebApi.IssueDto, root.ComicStockwebApi.OrderItemDto);
  }
}(this, function(ApiClient, IssueDto, OrderItemDto) {
  'use strict';




  /**
   * The OrderDto model module.
   * @module model/OrderDto
   * @version v1
   */

  /**
   * Constructs a new <code>OrderDto</code>.
   * @alias module:model/OrderDto
   * @class
   */
  var exports = function() {
    var _this = this;









  };

  /**
   * Constructs a <code>OrderDto</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/OrderDto} obj Optional instance to populate.
   * @return {module:model/OrderDto} The populated <code>OrderDto</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('total')) {
        obj['total'] = ApiClient.convertToType(data['total'], 'Number');
      }
      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'Number');
      }
      if (data.hasOwnProperty('orderDate')) {
        obj['orderDate'] = ApiClient.convertToType(data['orderDate'], 'Date');
      }
      if (data.hasOwnProperty('issue')) {
        obj['issue'] = IssueDto.constructFromObject(data['issue']);
      }
      if (data.hasOwnProperty('items')) {
        obj['items'] = ApiClient.convertToType(data['items'], [OrderItemDto]);
      }
      if (data.hasOwnProperty('deliveryStatus')) {
        obj['deliveryStatus'] = ApiClient.convertToType(data['deliveryStatus'], 'String');
      }
      if (data.hasOwnProperty('shipmentReference')) {
        obj['shipmentReference'] = ApiClient.convertToType(data['shipmentReference'], 'String');
      }
      if (data.hasOwnProperty('shipmentDate')) {
        obj['shipmentDate'] = ApiClient.convertToType(data['shipmentDate'], 'Date');
      }
    }
    return obj;
  }

  /**
   * @member {Number} total
   */
  exports.prototype['total'] = undefined;
  /**
   * @member {Number} id
   */
  exports.prototype['id'] = undefined;
  /**
   * @member {Date} orderDate
   */
  exports.prototype['orderDate'] = undefined;
  /**
   * @member {module:model/IssueDto} issue
   */
  exports.prototype['issue'] = undefined;
  /**
   * @member {Array.<module:model/OrderItemDto>} items
   */
  exports.prototype['items'] = undefined;
  /**
   * @member {module:model/OrderDto.DeliveryStatusEnum} deliveryStatus
   */
  exports.prototype['deliveryStatus'] = undefined;
  /**
   * @member {String} shipmentReference
   */
  exports.prototype['shipmentReference'] = undefined;
  /**
   * @member {Date} shipmentDate
   */
  exports.prototype['shipmentDate'] = undefined;


  /**
   * Allowed values for the <code>deliveryStatus</code> property.
   * @enum {String}
   * @readonly
   */
  exports.DeliveryStatusEnum = {
    /**
     * value: "Cancelled"
     * @const
     */
    "Cancelled": "Cancelled",
    /**
     * value: "Delivered"
     * @const
     */
    "Delivered": "Delivered",
    /**
     * value: "Pending"
     * @const
     */
    "Pending": "Pending"  };


  return exports;
}));


