/**
 * ComicStock.WebApi
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd && false) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.ComicStockwebApi) {
      root.ComicStockwebApi = {};
    }
    root.ComicStockwebApi.QualityInput = factory(root.ComicStockwebApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The QualityInput model module.
   * @module model/QualityInput
   * @version v1
   */

  /**
   * Constructs a new <code>QualityInput</code>.
   * @alias module:model/QualityInput
   * @class
   */
  var exports = function() {
    var _this = this;





  };

  /**
   * Constructs a <code>QualityInput</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/QualityInput} obj Optional instance to populate.
   * @return {module:model/QualityInput} The populated <code>QualityInput</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('fineQuantity')) {
        obj['fineQuantity'] = ApiClient.convertToType(data['fineQuantity'], 'Number');
      }
      if (data.hasOwnProperty('veryFineQuantity')) {
        obj['veryFineQuantity'] = ApiClient.convertToType(data['veryFineQuantity'], 'Number');
      }
      if (data.hasOwnProperty('goodQuantity')) {
        obj['goodQuantity'] = ApiClient.convertToType(data['goodQuantity'], 'Number');
      }
      if (data.hasOwnProperty('poorQuantity')) {
        obj['poorQuantity'] = ApiClient.convertToType(data['poorQuantity'], 'Number');
      }
    }
    return obj;
  }

  /**
   * @member {Number} fineQuantity
   */
  exports.prototype['fineQuantity'] = undefined;
  /**
   * @member {Number} veryFineQuantity
   */
  exports.prototype['veryFineQuantity'] = undefined;
  /**
   * @member {Number} goodQuantity
   */
  exports.prototype['goodQuantity'] = undefined;
  /**
   * @member {Number} poorQuantity
   */
  exports.prototype['poorQuantity'] = undefined;



  return exports;
}));


